config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :matches
  resources :athletes
  resources :expenses
  resources :incomes
  get "dashboard", to: "dashboard#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  has_many :payments, dependent: :destroy
  has_many :athlete_matches, dependent: :destroy
  has_many :matches, through: :athlete_matches

  validates :name, presence: true
  validates :phone, presence: true
  validates :date_of_birth, presence: true
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: %i[ show edit update destroy ]

  def index
    @athletes = Athlete.all
  end

  def show
  end

  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: "Athlete was successfully created." }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @athlete.errors, status: :unprocessable_content }
      end
    end
  end

  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: "Athlete was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @athlete.errors, status: :unprocessable_content }
      end
    end
  end

  def destroy
    @athlete.destroy!

    respond_to do |format|
      format.html { redirect_to athletes_path, notice: "Athlete was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    def athlete_params
      params.require(:athlete).permit(:name, :phone, :date_of_birth)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_athlete.html.erb
<div id="<%= dom_id athlete %>">
  <p>
    <strong>Name:</strong>
    <%= athlete.name %>
  </p>

</div>

app/views/athletes/_form.html.erb
<%= form_with(model: athlete) do |form| %>
  <% if athlete.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
        <% athlete.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<% content_for :title, "Editing athlete" %>

<h1>Editing athlete</h1>

<%= render "form", athlete: @athlete %>

<br>

<div>
  <%= link_to "Show this athlete", @athlete %> |
  <%= link_to "Back to athletes", athletes_path %>
</div>

app/views/athletes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Athletes" %>

<h1>Athletes</h1>

<div id="athletes">
  <% @athletes.each do |athlete| %>
    <%= render athlete %>
    <p>
      <%= link_to "Show this athlete", athlete %>
    </p>
  <% end %>
</div>

<%= link_to "New athlete", new_athlete_path %>

app/views/athletes/new.html.erb
<% content_for :title, "New athlete" %>

<h1>New athlete</h1>

<%= render "form", athlete: @athlete %>

<br>

<div>
  <%= link_to "Back to athletes", athletes_path %>
</div>

app/views/athletes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @athlete %>

<div>
  <%= link_to "Edit this athlete", edit_athlete_path(@athlete) %> |
  <%= link_to "Back to athletes", athletes_path %>

  <%= button_to "Destroy this athlete", @athlete, method: :delete %>
</div>