config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :matches
  resources :athletes
  resources :expenses
  resources :incomes
  get "dashboard", to: "dashboard#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/income.rb
class Income < ApplicationRecord
  self.inheritance_column = :_type_disabled
  belongs_to :transaction_category

  validates :unit_value, presence: true
  validates :date, presence: true

  def type
    transaction_category&.name
  end

  def type=(value)
    self.transaction_category = TransactionCategory.find_by(name: value)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: %i[ show edit update destroy ]

  def index
    @incomes = Income.all
  end

  def show
  end

  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: "Income was successfully created." }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @income.errors, status: :unprocessable_content }
      end
    end
  end

  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: "Income was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @income.errors, status: :unprocessable_content }
      end
    end
  end

  def destroy
    @income.destroy!

    respond_to do |format|
      format.html { redirect_to incomes_path, notice: "Income was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    def set_income
      @income = Income.find(params[:id])
    end

    def income_params
      params.require(:income).permit(:unit_value, :date, :transaction_category_id)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_with(model: income) do |form| %>
  <% if income.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<div id="<%= dom_id income %>">
</div>

app/views/incomes/edit.html.erb
<% content_for :title, "Editing income" %>

<h1>Editing income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Show this income", @income %> |
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Incomes" %>

<h1>Incomes</h1>

<div id="incomes">
  <% @incomes.each do |income| %>
    <%= render income %>
    <p>
      <%= link_to "Show this income", income %>
    </p>
  <% end %>
</div>

<%= link_to "New income", new_income_path %>

app/views/incomes/new.html.erb
<% content_for :title, "New income" %>

<h1>New income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @income %>

<div>
  <%= link_to "Edit this income", edit_income_path(@income) %> |
  <%= link_to "Back to incomes", incomes_path %>

  <%= button_to "Destroy this income", @income, method: :delete %>
</div>